sudo: false
os:
- linux
language: minimal
cache:
  directories:
  - "$HOME/.stack"
before_install:
- sudo apt-get update
- sudo apt-get install pandoc php php-curl
install:
- make
before_script: []
script:
- "! grep -P '<pre\\s*>' */*.md"
after_script: []
deploy:
- provider: pages
  local_dir: out_
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: false
  on:
    branch: master
env:
  global:
  - secure: lDDTCu13Kvdoun28EYqUUlgJqBQ/mgKC8/Zf3H3ESPznQXJESaYMA3EmQPYcHOzYk13oZuGZDwudA65Y97FgBxP4NXBLD0u/sveQV/a2uB48TgPfkGCZ5B1WsEwvZcbQdKAHyM4DO7QUF6KGrEbNCohhiA5HU2slch7deCqvp1SXERMcpYpMvEm0CqVxC5CGmt3G3Jg2ovttL+QwBgdxxmdKBE7diNEJxKIH5mBZtzG6QwerujXunkiS3SVP+4bNDXjtBxHtZAX4RDF7uhruX6WVdw32LoJ3mI16Lqo4DiMusv04hO+3tpaxzBd+BIiscRvwIMwsj+dpNkCIQDfRrHO345AP+QmjkA2hKwB+ENtvqo/ei0y9wO+R4Li+obA+zimtiauslNFMXMScvXhYTmxhvDZOn5OblbfWNlPeL2igpOarCdwWTZTP+JqI4KenxO6veTAgHJAsCUq9NE0Dr/riPE+JndkxBqCMqhnq9zOvMpF3h5pK/efFHWDed5uUsumvhUtR5xCXGHb5g2qJFABmgAJXmNKPbjAI0F8WSfms1854BMWFNfw0MHzVMCX5rbCka2vm2BVy5NkA+bVg2hwHXStfzeVDw4wwOCuyVt3XmH/Zk60Fi0i4PCzvr0Zs0WZCPw6DVRuB1qemjLugUwOQ9TWKvBXfPRzew4/8qLs=
