name: Deploy site to GitHub pages
on: push

jobs:
  linux1:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: update package database
      run: sudo apt-get update

    - name: install required packages
      run: sudo apt-get install pandoc yui-compressor php php-curl

  linux2:
    name: Checkout code
    needs: [linux1]
    steps:
    - name: checkout code
      uses: actions/checkout@v2.3.1

    - name: build the site
      run: make

    - name: look for todos
      run: "! grep -i -P '<pre\\s*>|TODO' */*.md"

