name: Deploy site to GitHub pages
on: push

jobs:
  linux:
    name: echo test
    runs-on: ubuntu-latest
    steps:
    - name: update package database
      run: sudo apt-get update
    - name: install required packages
      run: sudo apt-get install pandoc yui-compressor php php-curl
    - name: build the site
      run: make
    - name: look for todos
      run: "! grep -i -P '<pre\\s*>|TODO' */*.md"

